[build]
  publish = "public"
  functions = "functions"
  command = "pip install -r requirements.txt"
  command = "python -m venv env"
  command = "source env/bin/activate"
  command = "python -m pip install --upgrade pip"
  command = "python -m playwright install"
  command = "pip install pytest-playwright"
  command = "playwright install"


[build.environment]
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "false"

[[redirects]]
  from = "/run-test"
  to = "/.netlify/functions/run-automation"
  status = 200

#[build]
#  command = "pip install -r requirements.txt && playwright install && playwright install-deps"
#  functions = "netlify/functions"
#  publish = "."

#[[plugins]]npm install -D @netlify/plugin-pythonython"

#[build]
#  publish = "public"
#  functions = "functions"

