[build]
  publish = "public"
  functions = "functions"
  command = "pip install -r requirements.txt && playwright install chromium && playwright install-deps"

[[redirects]]
  from = "/run-test"
  to = "/.netlify/functions/run-automation"
  status = 200

#[build]
#  command = "pip install -r requirements.txt && playwright install && playwright install-deps"
#  functions = "netlify/functions"
#  publish = "."

#[[plugins]]npm install -D @netlify/plugin-pythonython"